version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: password-vault-db
    environment:
      POSTGRES_DB: password_vault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - password-vault-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: password-vault-app
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/password_vault
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - password-vault-network
#    restart: unless-stopped

volumes:
  postgres_data:
  maven_cache:

networks:
  password-vault-network:
    driver: bridge

